# Generated by Django 4.1.1 on 2024-03-07 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_genre_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='released',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.season'),
        ),
    ]
