# Generated by Django 4.1.1 on 2024-03-09 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_anime_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.lang'),
        ),
    ]
