# Generated by Django 4.1.1 on 2024-03-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_anime_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodes',
            name='comments',
            field=models.IntegerField(null=True),
        ),
    ]
